#!/bin/bash
PREPDIR="/Volumes/filestore/PREPPED"

SCRIPTDIR="$(dirname "$0")"
while read file ; do
    MEDIAID=$(basename "${file%.*}")
    echo "Working on ${file}"
    RS_ID=$("${SCRIPTDIR}/rs_search" "${MEDIAID}")
    if [[ -z "${RS_ID}" ]] ; then
        echo "${MEDIAID} does not appear in resourcespace, so uploading..."
        rs_uploadfile "${file}"
        prot2rs "${MEDIAID}"
        RS_ID=$("${SCRIPTDIR}/rs_search" "${MEDIAID}")
        if [[ -z "${RS_ID}" ]] ; then
            echo "Something went wrong and ${MEDIAID} does not appear to be in resourcespace."
            if [[ ! -d "${PREPDIR}/upload_error" ]] ; then
                mkdir "${PREPDIR}/upload_error"
            fi
            mv -v "${file}" "${PREPDIR}/upload_error/"
        else
            echo "Cleaning up and moving ${file} which is now at pages/view.php?ref=${RS_ID}."
            if [[ ! -d "${PREPDIR}/uploaded" ]] ; then
                mkdir "${PREPDIR}/uploaded"
            fi
            if [[ -f "${file}" ]] ; then
                rm -v "${file}"
            fi
        fi
    else
        echo "${MEDIAID} is already in resoursace at ${RS_ID} so going to skip uploading this."
        if [[ ! -d "${PREPDIR}/already_uploaded" ]] ; then
            mkdir "${PREPDIR}/already_uploaded"
        fi
        mv -v "${file}" "${PREPDIR}/already_uploaded/"
    fi
done < <(find "${PREPDIR}" -type f -size +0 -maxdepth 1)

