#!/bin/bash
#This script is used to clean up files that are more than a month old from the studio folder on the XSan Video. 

Cleanupdir="/Volumes/TigerVideo/studio"
find "$Cleanupdir" -type f -mtime +60d ! -path "*To_Archive*" ! -path "*To_Retain*"| while read file ; do
    movedir=$(dirname "$file" | sed "s|${Cleanupdir}|${Cleanupdir}/To_Archive|g")
    mkdir -p "$movedir/"
    mv -v -n "$file" "$movedir/"
done
