#!/bin/bash
PREPDIR="/Volumes/filestore/PREPPED"

SCRIPTDIR="$(dirname "$0")"
while read file ; do
    echo "Working on ${file}"
    rs_uploadfile "${file}"
    MEDIAID=$(basename "${file%.*}")
    prot2rs "${MEDIAID}"
    RS_ID=$("${SCRIPTDIR}/rs_search" "${MEDIAID}")
    if [[ -z "${RS_ID}" ]] ; then
        echo "Something went wrong and ${MEDIAID} does not appear to be in resourcespace."
    else
        echo "Cleaning up and removing ${file} which is now at pages/view.php?ref=${RS_ID}."
        if [[ -f "${file}" ]] ; then
            rm -v "${file}"
        fi
    fi
done < <(find "${PREPDIR}" -type f -size +0)
