#!/bin/bash
# This script sends an email when a new file is dropped off in the To Library folder. A cron job is set up to read the folder every 10 minutes. To edit the cron job, type crontab -e in the Terminal. 
searchdirectory="$1"
timefile=$HOME/.timefile_$(basename "${searchdirectory}")

_get_broadcastduration(){
    BROADCASTDURATION=$(mediainfo --inform="General;%Duration_String4%" "${1}")
}
_get_filesize(){
    FILESIZE=$(ls -hl "${1}" | awk '{print $5}')
}
_get_user(){
    USER=$(ls -hl "${1}" | awk '{print $3}')
}

if [ ! -f "${timefile}" ] ; then 
    filelist=$(find "${searchdirectory}" -type f ! -name .DS_Store)
else
    filelist=$(find "${searchdirectory}" -cnewer "${timefile}" -type f ! -name .DS_Store) 
fi
touch "${timefile}"

message="These new files showed up in $(basename "${searchdirectory}"):\n\n"

if [ -n "${filelist}" ] ; then
     BOUNDARY="unique-boundary-$RANDOM"
     while read file ; do
        _get_broadcastduration "$file"
        _get_filesize "$file"
        _get_user "$file"
        message+="*********\n"
        message+="Filename: $file\n"
        if [ -n "${BROADCASTDURATION}" ] ; then
            message+="Duration: $BROADCASTDURATION\n"
        fi
        if [ -n "${FILESIZE}" ] ; then
            message+="Size: $FILESIZE\n"
        fi
        if [ -n "${USER}" ] ; then
            message+="User: $USER\n\n\n"
        fi
        if [ -n "${BROADCASTDURATION}" ] ; then
            makegifsummary -o /tmp "$file"
            gifpath="/tmp/$(basename "${file%.*}").gif"
            if [ -f "${gifpath}" ] ; then
                ATT_MIMETYPE=$(file -Ib "${gifpath}" | cut -d";" -f1)
                ATT_ENCODED=$(base64 < "${gifpath}")
                message+="--$BOUNDARY\n"
                message+="Content-Type: $ATT_MIMETYPE; name="$(basename "${gifpath}")"\n"
                message+="Content-Transfer-Encoding: base64\n"
                message+="Content-Disposition: attachment; filename="$(basename "${gifpath}")"\n"
                message+="\n"
                message+="$ATT_ENCODED"
                message+="\n\n"
                message+="--$BOUNDARY"
                message+="\n"
            fi
        fi
        message+="\n"
    done < <(echo "${filelist}")

    cat <<EOF | sendmail -f "library@cuny.tv" -F "library@cuny.tv" "library@cuny.tv"
MIME-Version: 1.0
From: "library@cuny.tv"
To: "library@cuny.tv"
Subject: [New Files on $(basename "${searchdirectory}")]
Content-Type: multipart/mixed; boundary="$BOUNDARY"

--$BOUNDARY
Content-Type: text/plain
Content-Disposition: inline

$(echo -e "${message}")

Enjoy!



--$BOUNDARY--

EOF
fi
