#!/bin/bash
SCRIPTDIR="$(dirname "${0}")"
curl -s "http://10.10.201.48/fmi/xml/fmresultset.xml?-db=CUNY_TV_archive&-lay=pbcoreform&PBCoreInstantiationIdentifier::instantiationIdentifier=${1}&-find" | xsltproc "${SCRIPTDIR}/fm2pbcore.xsl" -
